### ISSUE TITLE
NullPointerException/IllegalMonitorStateException during VaadinService::fireSessionDestroy

### ISSUE THREAD

**Issue by sevenzebras** [vaadin/multiplatform-runtime#109]
After upgrading to MPR 2.2.7 which included a fix for issue #104 we are still experiencing problems with unexpected session timeouts. The IllegalMonitorStateException is pretty similar to #104 but now we also occasionally get NullPointerExceptions. We sadly still can’t provide steps to reproduce the issue. Maybe the attached stacktraces give a hint.

Versions:
Vaadin Framework -> 8.14.3
Flow -> 14.8.4
MPR -> 2.2.8
CDI -> 11.3.0
JBoss EAP 7.4.3 (Undertow)

**NPE1:**
Caused by: java.lang.NullPointerException
StackTrace: java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.FutureTask.get(FutureTask.java:192)
com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2075)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1016)
com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:646)
com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:214)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)
Cause: 
com.vaadin.mpr.core.AbstractMprUIProvider.lambda$createInstance$d1cfe78c$1(AbstractMprUIProvider.java:55)
com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)
com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194)
com.vaadin.flow.component.Component.fireEvent(Component.java:358)
com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:386)
com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:264)
java.util.Optional.ifPresent(Optional.java:159)
com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:109)
java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:351)
com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:845)
com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:341)
com.vaadin.flow.internal.StateNode.setParent(StateNode.java:280)
com.vaadin.flow.internal.StateTree$RootNode.setParent(StateTree.java:65)
com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:401)
com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:623)
com.vaadin.flow.server.VaadinService.lambda$null$65d65655$1(VaadinService.java:665)
com.vaadin.flow.component.UI.accessSynchronously(UI.java:435)
com.vaadin.flow.component.UI.accessSynchronously(UI.java:396)
com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:655)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2072)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1016)
com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:646)
com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:214)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)

**NPE2:**
Caused by: java.lang.NullPointerException
StackTrace: java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.FutureTask.get(FutureTask.java:192)
com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2075)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1016)
com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:646)
com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:214)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)
Cause: 
com.vaadin.flow.server.communication.AtmospherePushConnection.disconnect(AtmospherePushConnection.java:345)
com.vaadin.flow.component.internal.UIInternals.setPushConnection(UIInternals.java:453)
com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:405)
com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:623)
com.vaadin.flow.server.VaadinService.lambda$null$65d65655$1(VaadinService.java:665)
com.vaadin.flow.component.UI.accessSynchronously(UI.java:435)
com.vaadin.flow.component.UI.accessSynchronously(UI.java:396)
com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:655)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2072)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1016)
com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:646)
com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:214)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)

**IllegalMonitorStateException:**
Caused by: java.lang.IllegalMonitorStateException
StackTrace: java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.FutureTask.get(FutureTask.java:192)
com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2075)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.mpr.core.MprServletService.accessSession(MprServletService.java:165)
com.vaadin.server.VaadinSession.access(VaadinSession.java:1421)
com.vaadin.server.VaadinService.fireSessionDestroy(VaadinService.java:531)
com.vaadin.server.VaadinSession.valueUnbound(VaadinSession.java:313)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)
Cause: 
java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:729)
com.vaadin.mpr.core.MprSession.unlock(MprSession.java:75)
com.vaadin.ui.UI.accessSynchronously(UI.java:1513)
com.vaadin.server.VaadinService.lambda$fireSessionDestroy$1(VaadinService.java:540)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2072)
com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2038)
com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2005)
com.vaadin.mpr.core.MprServletService.accessSession(MprServletService.java:165)
com.vaadin.server.VaadinSession.access(VaadinSession.java:1421)
com.vaadin.server.VaadinService.fireSessionDestroy(VaadinService.java:531)
com.vaadin.server.VaadinSession.valueUnbound(VaadinSession.java:313)
io.undertow.servlet.core.SessionListenerBridge.attributeRemoved(SessionListenerBridge.java:145)
io.undertow.server.session.SessionListeners.attributeRemoved(SessionListeners.java:81)
io.undertow.server.session.InMemorySessionManager$SessionImpl.removeAttribute(InMemorySessionManager.java:585)
io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:103)
io.undertow.servlet.core.SessionListenerBridge.access$000(SessionListenerBridge.java:41)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:54)
io.undertow.servlet.core.SessionListenerBridge$1.call(SessionListenerBridge.java:51)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1551)
io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:73)
io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:618)
io.undertow.server.session.InMemorySessionManager$SessionImpl$2$1.run(InMemorySessionManager.java:415)
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
java.lang.Thread.run(Thread.java:748)

**Comment by sevenzebras** [comment]
We are now able to reproduce at least some part of the issue. First it seems to make a difference whether you actively close idle sessions (web.xml > closeIdleSessions=true) or not. Second whether the browser is still open or was closed by the user and third if you invalidate the HTTPSession in an SessionDestroyListener or not (having more than one VaadinSession per HTTPSession). 

We now decided to work with closeIdleSessions=false and invalidate the HTTPSession in a SessionDestroyListener since we only run one Service. This basically reduces the logged exceptions to one case that is at least in our case quite reproducible and does not affect the user anymore but still causes noise in the logs and raises the question if there is possibly another impact.
The way we can reproduce the issue is by opening at least two tabs in chrome, navigate around a little bit (most of the time opening one view seems to be enough) an the disconnect the network via dev tools und wait for the session timeout. Closing the browser produces the exception in some cases but cutting the network seems to be a lot more reliant.

Prior to the NPE you get kind of an expected TimeoutException:
Timeout waiting for messages to be sent to client before disconnect: java.util.concurrent.TimeoutException
	at org.atmosphere.cpr.BroadcasterFuture.get(BroadcasterFuture.java:126)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.disconnect(AtmospherePushConnection.java:331)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.vaadin.mpr.core.MprPushConnection.disconnect(MprPushConnection.java:48)
	at com.vaadin.ui.UI.setPushConnection(UI.java:1749)
	at com.vaadin.mpr.core.AbstractMprUI.setPushConnection(AbstractMprUI.java:100)
	at com.vaadin.ui.UI.lambda$setSession$0(UI.java:525)
	at java.lang.Thread.run(Thread.java:748)
