### ISSUE TITLE
Session expiration under MPR | Not redirect to login page

### ISSUE THREAD

**Issue by melihkurtaran** [vaadin/multiplatform-runtime#113]
There is an issue with session expiring after the defined threshold. The underlying http session is killed, session expired URL default setting is null and that should refresh the page, but it does not refresh.

It can be reproduced with following demo app from Vaadin
https://www.dropbox.com/s/qyhl2ec2un5wo8r/my-app.zip?dl=0

Neither

changes in application.properties file:
server.servlet.session.timeout=300

or

On MainLayout.java overridden onAttach() method and set session timeout to 5 min. 
 VaadinSession.getCurrent().getSession().setMaxInactiveInterval(300);

does not work to redirect to login page after session expiration.

It is run with the parameters:
-Dvaadin.closeIdleSessions=true -Dvaadin.heartbeatInterval=60

**Comment by mcollovati** [comment]
I did some test and I can see that the http session is not destroyed.
After the session timeout interval, the Vaadin session is destroyed during heartbeat request; the request handler responds with an 403 error with "Session expired" message and the browser page is refreshed, but since the http session is still active, the authentication details are still there.

To have logout performed due to inactivity we can force invalidation of the http session when Vaadin session expires, for example with a `SessionDestroyListener`


```java
@Bean
VaadinServiceInitListener invalidateHttpSessionOnVaadinSessionDestroy() {
    return event -> event.getSource().addSessionDestroyListener(
            sessionEvent -> sessionEvent.getSession().getSession().invalidate()
    );
}
```

Let me know if I am missing something or if I have misunderstood the original question

**Comment by rahullakhangaonkar** [comment]
We were trying to register the SessionDestory handler using below code
VaadinServlet.getCurrent().getService().addSessionDestroyListener(
                    sessionEvent -> sessionEvent.getSession().getSession().invalidate()
);
written in MainView onAttach method. It was not working
After adding the code
@Bean
VaadinServiceInitListener invalidateHttpSessionOnVaadinSessionDestroy() {
    return event -> event.getSource().addSessionDestroyListener(
            sessionEvent -> sessionEvent.getSession().getSession().invalidate()
    );
}
It worked for the sample attached in the https://www.dropbox.com/s/qyhl2ec2un5wo8r/my-app.zip?dl=0
However even after putting invalidateHttpSessionOnVaadinSessionDestroy in our application it is not working.

**Comment by mcollovati** [comment]
Hi, @rahullakhangaonkar 
thanks for your feedback.

Can you please provide some additional detail about your application?
What Vaadin version are you using?
Are you using the Vaadin spring addon?
Is the session destroy listener not invoked at all?
Have you double checked that the `VaadinServiceInitListener` is correctly registered?

**Comment by rahullakhangaonkar** [comment]
In our application what we observed that invalidateHttpSessionOnVaadinSessionDestroy  event handling method sessionEvent.getSession().getSession().invalidate() is not  getting called at timeout. Also on that timeframe it generates multiple logs like
2022-07-11 11:25:34 ERROR [https-jsse-nio-9443-exec-4]: o.a.c.c.C.[.[.[.[springServlet]:175 - Servlet.service() for servlet [springServlet] threw exception
java.lang.RuntimeException: Push failed
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:200)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:175)
	at com.vaadin.flow.component.UI.push(UI.java:702)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:721)
Caused by: com.vaadin.ui.UIDetachedException: null
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1498)
	at com.vaadin.mpr.core.AbstractLegacyEmbed.writeResponse(AbstractLegacyEmbed.java:102)
	at com.vaadin.mpr.core.AbstractLegacyEmbed.lambda$scheduleResponse$2f364bb9$1(AbstractLegacyEmbed.java:88)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)

and 
2022-07-11 11:25:34 ERROR [https-jsse-nio-9443-exec-4]: o.a.c.c.C.[.[.[.[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/appname] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Push failed] with root cause
com.vaadin.ui.UIDetachedException: null
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1498)
	at com.vaadin.mpr.core.AbstractLegacyEmbed.writeResponse(AbstractLegacyEmbed.java:102)
	at com.vaadin.mpr.core.AbstractLegacyEmbed.lambda$scheduleResponse$2f364bb9$1(AbstractLegacyEmbed.java:88)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392)


and 
2022-07-11 11:25:34 ERROR [https-jsse-nio-9443-exec-4]: o.a.c.c.C.[.[.[.[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] threw exception
java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:578)
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:592)
	at com.vaadin.flow.server.VaadinSession.getAttribute(VaadinSession.java:827)

and
2022-07-11 11:41:39 ERROR [https-jsse-nio-9443-exec-1]: o.a.c.c.C.[.[.[.[springServlet]:175 - Servlet.service() for servlet [springServlet] threw exception
java.lang.NullPointerException: Cannot invoke "com.vaadin.mpr.core.MprSession.removeUI(com.vaadin.ui.UI)" because "mprSession" is null
	at com.vaadin.mpr.core.AbstractMprUIProvider.lambda$createInstance$d1cfe78c$1(AbstractMprUIProvider.java:54)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:378)

**Comment by rahullakhangaonkar** [comment]
Hi @mcollovati,
Thanks for your reply.

What Vaadin version are you using?
We are using Vaddin - 23.0.3 and mpr version 6.0.1

Are you using the Vaadin spring addon?
yes
<dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring</artifactId>
        </dependency>

Is the session destroy listener not invoked at all?
No session destroy listener is not getting called and sow some errors in log file. which I have pasted above. it only come around timeout time so there is some relationship for these errors

Have you double checked that the VaadinServiceInitListener is correctly registered?
Yes On startup VaadinServiceInitListener is correctly registered I put a breakpoint on startup and it did come for registration.

**Comment by mcollovati** [comment]
> 2022-07-11 11:41:39 ERROR [https-jsse-nio-9443-exec-1]: o.a.c.c.C.[.[.[.[springServlet]:175 - Servlet.service() for servlet [springServlet] threw exception
java.lang.NullPointerException: Cannot invoke "com.vaadin.mpr.core.MprSession.removeUI(com.vaadin.ui.UI)" because "mprSession" is null
at com.vaadin.mpr.core.AbstractMprUIProvider.lambda$createInstance$d1cfe78c$1(AbstractMprUIProvider.java:54)
at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195)
at com.vaadin.flow.component.Component.fireEvent(Component.java:378)

This is weird, because it seems that the NPE has been fixed in 6.0.1.
If I check `AbstractMprUIProvider` source code at line 54 i can see this
```
  if (mprSession != null) {    // This is line 54
   mprSession.removeUI(oldUi);
  }
```

**Comment by rahullakhangaonkar** [comment]
Hi @mcollovati,
I checked dependency:tree and due to multi module it was picking 6.0.0 at application class level
We have one module which has StartupClass with main method and other module with Vaadin 23  and other module with v8. 
I have ensure complete project is now using mpr-v8 with version 6.0.1 and it help in reducing some error like NPE. even Push error is not observed but still below error remains and Destory handler did not get called

2022-07-11 13:52:04 ERROR [https-jsse-nio-9443-exec-9]: o.a.c.c.C.[.[.[.[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/appname] threw exception
java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:578)
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:592)
	at com.vaadin.flow.server.VaadinSession.getAttribute(VaadinSession.java:827)
	at com.vaadin.flow.server.SessionRouteRegistry.getSessionRegistry(SessionRouteRegistry.java:76)
	at com.vaadin.flow.router.Router.getRegistry(Router.java:302)
	at com.vaadin.flow.spring.security.RequestUtil.isAnonymousRoute(RequestUtil.java:140)
	at org.springframework.security.web.access.intercept.DefaultFilterInvocationSecurityMetadataSource.getAttributes(DefaultFilterInvocationSecurityMetadataSource.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:186)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:113)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:150)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:142)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcollovati** [comment]
@rahullakhangaonkar thanks for double checking your project and for feedback.
I'm able to reproduce the error with Push.
I'll also take a look a this new exception related to spring security Vaadin integration

**Comment by mcollovati** [comment]
@rahullakhangaonkar I cannot reproduce the issue with `RequestUtil.isAnonymousRoute` from the last stacktrace.
When does it happen? Can you provide some step or advice  to reproduce it?

**Comment by rahullakhangaonkar** [comment]
Hi @mcollovati I have also tried reproducing this issue on some sample codes from Vaadin but I was not able to reproduce this issue. but this issue is very easily reproduce in my application. Now I am not sure what pointers will help you in getting more information about this issue

**Comment by mcollovati** [comment]
@rahullakhangaonkar can you detect what request originates the error (request URI)?
Does it happen after session expiration? Can you share your spring security configuration?

**Comment by mcollovati** [comment]
Hi @rahullakhangaonkar, we published a SNAPSHOT version with some fixes.
Do you mind giving it a try?

You may need to add vaadin pre-releases repository to the POM file and change MPR version to 6.0-SNAPSHOT

```xml
        <repository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

**Comment by rahullakhangaonkar** [comment]
@mcollovati I will try this

**Comment by rahullakhangaonkar** [comment]
@mcollovati for your previous question what request originates the error (request URI)?
after heartbeat url https://localhost:9443/appname/?v-r=heartbeat&v-uiId=1
Below url gets called 
https://localhost:9443/appname/vaadinServlet/?v-r=push&v-uiId=1&v-pushId=d2aee0a8-fb79-4c48-9963-0ef868b091e0&X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=f0d0f008-c21c-40d9-8a6d-f33f60618e3d
After this url page on which we were there gets called like
https://localhost:9443/appname/viewname

**Comment by rahullakhangaonkar** [comment]
@mcollovati when I use MPR version to 6.0-SNAPSHOT Looks like it was redirected to login page properly. It worked locally for me. but give me a day more to confirm again.

**Comment by mcollovati** [comment]
@rahullakhangaonkar thank you very much for your feedback

**Comment by rahullakhangaonkar** [comment]
@mcollovati on my prod environment even after using  MPR version to 6.0-SNAPSHOT my Destory even handler did not get called and in uncaugh exception handler I saw below error when page get refreshed
2022-07-14 07:39:55 ERROR [https-openssl-apr-8443-exec-2]: c.m.t.p.u.MainView:124 - Uncaught UI exception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Push failed
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
        at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2064)
        at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:713)
        at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1506)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1581)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
Caused by: java.lang.RuntimeException: Push failed
        at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:200)
        at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:175)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.vaadin.mpr.core.MprPushConnection.push(MprPushConnection.java:42)
        at com.vaadin.ui.UI.close(UI.java:1378)
        at com.vaadin.mpr.core.AbstractMprUI.close(AbstractMprUI.java:106)
        at com.vaadin.mpr.core.AbstractMprUI.lambda$init$5df2f1e0$1(AbstractMprUI.java:72)
        at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
        at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:19
Caused by: java.lang.NullPointerException: Cannot invoke "org.atmosphere.cpr.AtmosphereResource.getBroadcaster()" because the return value of "com.vaadin.flow.server.communication.AtmospherePushConnection.getResource()" is null
        at com.vaadin.flow.server.communication.AtmospherePushConnection.sendMessage(AtmospherePushConnection.java:215)
        at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:198)
        ... 162 common frames omitted

url which get called when this error come is
https://serverip:9443/appname/vaadinServlet/?v-r=push&v-uiId=0&v-pushId=18461ff7[…]Atmosphere-tracking-id=794b38cf-3e47-4fae-bd4a-9ab440cd937f
1:12

then

https://serverip:9443/appname/viewname (which this time returns 200 expected to return 302 for login page)

**Comment by mcollovati** [comment]
Hi @rahullakhangaonkar, we published another snapshot with a change that hopefully fixes `RuntimeException: Push failed` error.
May I ask you to give it a try? 
You should perhapse use the `-U` flag with maven, to force snapshot updates

**Comment by rahullakhangaonkar** [comment]
Hi @mcollovati we have tested with newly updated changes and it worked correctly and timeout happens. Thanks for all your support and help in resolving this issue.

**Comment by rahullakhangaonkar** [comment]
When this issue fix will be part of main release?

**Comment by mcollovati** [comment]
Version 6.0.2 is out. It will be part of the next Vaadin platform release
