### ISSUE TITLE
Gradle 7 + mpr + Vaadin 24 does not work because of the devsoap plugin

### ISSUE THREAD

**Issue by Artur-** [vaadin/multiplatform-runtime#117]
The test for Flow 24 + mpr + Vaadin 8 in the Flow project was disabled in https://github.com/vaadin/flow/pull/14937 because the devsoap plugin does not work with Gradle 7:
```
    Caused by: org.gradle.api.InvalidUserCodeException: Please use the ObjectFactory.listProperty() method to create a property of type List<T>.
        at org.gradle.api.internal.model.DefaultObjectFactory.property(DefaultObjectFactory.java:154)
        at org.gradle.api.model.ObjectFactory$property.call(Unknown Source)
        at com.devsoap.plugin.extensions.AddonExtension.<init>(AddonExtension.groovy:41)
        at com.devsoap.plugin.extensions.AddonExtension_Decorated.<init>(Unknown Source)

```

There is a 2.0.0 beta version of the devsoap plugin that was done before the project was abandoned but that one does not work either.

**Comment by mcollovati** [comment]
Updating the devsoap plugin to the latest beta and adding a workaround to redefine the [removed](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal=) `compile` configuration seems to makes the test pass.

```
configurations {
    compile
    compile.extendsFrom(implementation)
}
```
