### ISSUE TITLE
Initial navigation of v7 UI problematic on v10 UI init

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/multiplatform-runtime#16]
The initial navigation of the v7 UI triggers sometimes unwanted behaviour, when the v10 UI is initialized. I use the default navigator and a self implemented displayment of  v7 views inside a v10 view.

**Example paths**:
/ - route of the v10 view, that contains the legacy wrapped v7 css layout
/my-example - route to a v10 view

**Use case 1**
I have a v7 default view and go to `localhost:8080` via browser URL bar (not via Navigator).
The v7 and v10 UIs are initiated, the v10 container and v7 default views are shown. Thats correct behaviour.

**Use case 2**
I have a v7 default view and go to `localhost:8080/my-example` via browser URL bar (not via Navigator). Vaadin shows for a few milliseconds my v10 view and navigates then to the v7 default view. The same behavior occurs, when I navigate via navigator to the my-example view and refresh the browser page. That is unwanted behavior and intransparent to the user, since he cannot use for bookmarks or browser history.

**Use case 3**
I **don't** have a v7 default view. When the v7 and v10 UIs are initiated, I get the an exception thrown from the v7 UI that wants to navigate to the not existing default view. (exception see below)

**Conclusion** 
In use cases 2 and 3 the call of the default v7 view is wrong and should be avoided. I guess a more intelligent Navigator that knows about the V10 view states could help here. 

**Exception of UC 3**
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Trying to navigate to an unknown state '' and an error view provider not present
	at com.xyz.portal.ui.ApplicationErrorHandler.error(ApplicationErrorHandler.java:30)
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1464)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1447)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
...
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Trying to navigate to an unknown state '' and an error view provider not present
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:567)
	at com.vaadin.ui.UI.doInit(UI.java:698)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:222)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
	at com.vaadin.mpr.MprUIInitHandler.synchronizedHandleRequest(MprUIInitHandler.java:73)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	... 91 common frames omitted
```

**Comment by caalador** [comment]
What about using the MprNavigator?

**Comment by stefanuebe** [comment]
Usecase 2 is the same. Still navigating to the default v7 view. IMO this is the most annoying use case, since it will happen with every page reload or calling the page via a link.
Usecase 3 is handled, but shows nothing useful in my case (so page would need some special handling for that use case).

Nevertheless, the MprNavigator needs a MprNavigatorRoute to work, what is not suitable for this customers use case. A more independent MprNavigator that can also handle Use case 2 out of the box would be preferable.

**Comment by caalador** [comment]
Well basically the MprNavigator should work fine with getting a NavigationTarget (Flow route target that contains the component container) instead of the MprNavigatorRoute.
